import React from 'react';
import {
  PlayCircle,
  Monitor,
  Megaphone,
  Briefcase,
  MessageSquare,
  FileText,
  BarChart3,
  Lightbulb,
  Target,
  Users,
  Zap,
  Globe,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Star,
  Heart,
  Share2,
  Download,
  Upload,
  Search,
  Settings,
  HelpCircle,
  Info,
  AlertCircle,
  CheckCircle,
  XCircle,
  Edit,
  Trash2,
  Plus,
  Minus,
  ChevronRight,
  ChevronDown,
  Sparkles,
  BookOpen,
  GraduationCap,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Percent,
  PieChart,
  LineChart,
  Activity,
  Award,
  Flag,
  Home,
  Building2,
  Factory,
  Store,
  Truck,
  Package,
  ShoppingCart,
  CreditCard,
  Wallet,
  Banknote,
  Coins,
  type LucideIcon,
} from 'lucide-react';

export const SIMULATION_ICON_DEFAULT = 'PlayCircle';

export const simulationIconMap: Record<string, LucideIcon> = {
  PlayCircle,
  Monitor,
  Megaphone,
  Briefcase,
  MessageSquare,
  FileText,
  BarChart3,
  Lightbulb,
  Target,
  Users,
  Zap,
  Globe,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Star,
  Heart,
  Share2,
  Download,
  Upload,
  Search,
  Settings,
  HelpCircle,
  Info,
  AlertCircle,
  CheckCircle,
  XCircle,
  Edit,
  Trash2,
  Plus,
  Minus,
  ChevronRight,
  ChevronDown,
  Sparkles,
  BookOpen,
  GraduationCap,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Percent,
  PieChart,
  LineChart,
  Activity,
  Award,
  Flag,
  Home,
  Building2,
  Factory,
  Store,
  Truck,
  Package,
  ShoppingCart,
  CreditCard,
  Wallet,
  Banknote,
  Coins,
};

export const simulationIconNames = Object.keys(simulationIconMap).sort();

export function getSimulationIcon(iconName?: string | null): LucideIcon {
  if (!iconName?.trim()) return PlayCircle;
  return simulationIconMap[iconName] ?? PlayCircle;
}

export function SimulationIcon({ name, className }: { name?: string | null; className?: string }) {
  const Icon = getSimulationIcon(name);
  return <Icon className={className} />;
}
